fix media player supported features
alandtse/alexa_media_player pull request #2150
Opened 2023-12-28 19:08 UTC by Petro31

Fixes change in 2024.1 for supported features.

Fixes https://github.com/alandtse/alexa_media_player/issues/2149

2023-12-28 20:04 UTC, larena1 commented on custom_components/alexa_media/media_player.py
> +from homeassistant.components.media_player.const import MEDIA_TYPE_MUSIC
That is also deprecated

2023-12-28 20:45 UTC, MJHeijster commented
Thanks, hope it gets merged soon!

2023-12-28 21:08 UTC, alandtse commented
I guess we need to bumps hacs.json to set a new minimum version of HA.

2023-12-29 01:17 UTC, alandtse requested changes
Please bump this line to cover the new HA version 2024.1. https://github.com/alandtse/alexa_media_player/blob/dev/hacs.json#L6. Also, can you check on the comment about the deprecation of `MEDIA_TYPE_MUSIC`. Ideally we can handle them all at the same time.

2023-12-29 11:07 UTC, airy10 commented
Just confirming that it's fixing it for me, including the updating of sensors devices attached to a player

2023-12-29 12:15 UTC, Petro31 commented
FYI, I didn't change STATE_UNAVAILABLE.  That's supposed to be handled by the available property only, not in the state.  I'll let you decide what to do with that.

When the state property returns None, the state will be translated to `unknown`.  When the availability property returns False, the state will translate to `unavailable`.

2023-12-30 05:40 UTC, merged

2023-12-30 05:40 UTC, alandtse commented
Thanks!